name: Univerifier
version: '${project.version}'
main: com.mountaineercraft.univerifier.Univerifier
api-version: '1.21'
commands:
  verify:
    description: Verify that a player is a student
    usage: /<command> <email>
    permission: univerifier.verify
permissions:
  univerifier.verify:
    description: Allows the player to verify their student status
    default: true
  univerifier.verified:
    description: Allows the player to be verified as a student
    default: false